### ISSUE TITLE
Support for v2 and stream

### ISSUE THREAD

**Issue by ryo-ma** [ryo-ma/gpt-assistants-api-ui#10]
https://platform.openai.com/docs/assistants/overview?context=with-streaming

**Comment by bayrami1** [comment]
I was going to implement this on my own apps UI I might be able to help here, new to development but let me know if there is anything specific I can help with

**Comment by ryo-ma** [comment]
Your contributions are welcome.
However, if you are a beginner, the issue may be difficult.

**Comment by ryo-ma** [comment]
Done
