### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by chris77TNow** [ryo-ma/gpt-assistants-api-ui#12]
Hello,

Getting this error intermittently when chatting with the assistant, could you please advise?

IndexError: list index out of range
File "app.py", line 101, in get_message_value_list
message_content = message.content[0].text

Thanks!
C

**Comment by ryo-ma** [comment]
Thank you for the issue

There may be cases where there is no content at all.
I'll try to fix that bug.

**Comment by ryo-ma** [comment]
@chris77TNow If you check carefully, it's an old version code.
Currently, the code is as follows, and it supports streaming.

https://github.com/ryo-ma/gpt-assistants-api-ui/blob/main/app.py

Please try this.

**Comment by chris77TNow** [comment]
Thank you very much for this, works great!
