### ISSUE TITLE
Authenticate page

### ISSUE THREAD

**Issue by vietnguyengit** [ryo-ma/gpt-assistants-api-ui#14]
Hi, first of all, thank you for making this high-quality open-source project! I'm wondering if you have any plans to implement an authentication page. There is no need to use an external database for user credentials; it can be as simple as having hard-coded environment variables in a .env file, for example.

**Comment by ryo-ma** [comment]
I have no immediate plans to implement that feature.
If you are willing to contribute, I will accept it.

**Comment by vietnguyengit** [comment]
Ah cool, thanks @ryo-ma! I wanted to fork your repo to do that. It would be great if you'd accept it into the mainstream.

**Comment by vietnguyengit** [comment]
PR is up https://github.com/ryo-ma/gpt-assistants-api-ui/pull/19 @ryo-ma
