### ISSUE TITLE
Switching assistants

### ISSUE THREAD

**Issue by vietnguyengit** [ryo-ma/gpt-assistants-api-ui#16]
I'm just creating the issue here to track future PR if I attempt to do, and in case, you will accept.

Currently, each instance of this app can hold just 1 assistant id. I have multiple assistants with different purposes. If I can switch between them from the same instance, it would be very convenient.

**Comment by ryo-ma** [comment]
Sounds good.

**Comment by Haochi1222** [comment]
> I'm just creating the issue here to track future PR if I attempt to do, and in case, you will accept.
> 
> Currently, each instance of this app can hold just 1 assistant id. I have multiple assistants with different purposes. If I can switch between them from the same instance, it would be very convenient.

Hi bro, do you achieve it? It sounds really good.

**Comment by vietnguyengit** [comment]
@Haochi1222 hi, thank you, yes the PR has been up for the @ryo-ma to review, if you want to try now, you can check it out in my folked repo.
